production:
  tags:
  - debian-ch
  stage: deploy
  script:
  - mkdir -p ~/.ssh
  - echo $PWD
  - echo $HOME
  - echo -e "$DEPLOY_KEY" > ~/.ssh/id_dsa
  - chmod 600 ~/.ssh/id_dsa
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh deploy@buzz.debian.ch "
    cd /var/www/ &&
    git pull
    "
pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master
